library(maps)
a=map("state",plot=FALSE,fill=TRUE)
state=data.frame(x=a$x,y=a$y)
state$state=cumsum(is.na(a$x))+1
state$state=a$names[state$state]
state=state[-which(is.na(a$x)),]
state$state=gsub(":.*$","",state$state)
state$abbr=usCapitals[state$state,2]
statenbrs=nbrlist(state$abbr,state$x,state$y)
