##' Draw a circle
##' 
##' @param xvec x-coordinates
##' @param yvec y-coordinates
##' @param rvec radii
##' @param vertex the number of vertices of the circle
##' @param border color of border
##' @param col color to render in circle
##' @param add Whether the circles are added to another plot.
##' @export
##' @examples
##' x=y=1:5
##' r=5:1/5
##' circle(x,y,r,add=FALSE,asp=1)
##'
circle = function(xvec,yvec,rvec,vertex=100,border=1,col=NULL,add=TRUE,...){
    # This function is used to compute the locations of the circle border 
    # and draw multiple circles.
    # Borrowing the code from plotrix::draw.circle
    n=length(xvec)
    stopifnot(length(yvec)==n && n==length(rvec))
    if (length(border) < n)  border = rep(border, length.out = n)
    if (!is.null(col) && length(col) < n) col = rep(col, length.out = n)
    # xylim = par("usr")
    # plotdim = par("pin")
    # ymult = (xylim[4] - xylim[3])/(xylim[2] - xylim[1]) * plotdim[1]/plotdim[2]
    angle.inc = 2 * pi / vertex
    angles = seq(0, 2 * pi - angle.inc, by = angle.inc)
    if (!add) plot(c(min(x-r),max(x+r)),c(min(y-r),max(y+r)),type='n',xlab='x',ylab='y',...)
    for (i in 1:n){
        xv <- cos(angles) * rvec[i] + xvec[i]
        yv <- sin(angles) * rvec[i] + yvec[i]
        polygon(xv, yv, border = border[i], col = col)
    }
}

##' Find the nearest k neighbors
##' 
##' @param dismtrx The matrix of distance, typically generated by dist().
##' @param k The number of nearest neighbors that are chosen.
##' @return A data frame of indice. For each row, the i th cell is its i th nearest neighbor.
##' @export
##' @examples
##' data(usCapitals)
##' capital_dist=as.matrix(dist(usCapitals[,4:5]))
##' capital_neighbor_3=nnbr(capital_dist)
##' capital_neighbor_5=nnbr(capital_dist, 5)
##' 
nnbr = function(distmtrx,k=3){
    stopifnot(k < nrow(distmtrx))
    res=apply(distmtrx,1,function(xv){order(xv)[1:(k+1)]})
    res=t(res)[,2:(k+1)]
    if (k>1) colnames(res)=paste('N',1:k,sep='')
    return(res)
}

##' Find all the neighbors for the polygons by checking duplicated coordinates.
##' 
##' @param region Region names.
##' @param x X-coordinates.
##' @param y Y-coordinates.
##' @return "nbr" and "centroid". nbr is a list of neighbors, while centroid is the coordinates of polygon centroids.
##' @export
##' @examples
##' data(usCapitals)
##' state_nbrs=nbrlist(state$abbr,state$x,state$y)
##' 
nbrlist = function(region,x,y){
    stopifnot(length(x)==length(region) && length(y)==length(region))
    library(maps)
    digitx = max(min(nchar(as.character(x))),5)
    digity = max(min(nchar(as.character(y))),5)
    dat=data.frame(r=region,x=x,y=y)
    dat$r=as.character(dat$r)
    dat$p=paste(round(dat$x,digitx),round(dat$y,digity))
    dat=dat[!duplicated(dat),]
    censordat=dat[duplicated(dat$p)|duplicated(dat$p,fromLast=TRUE),]
    uniregion=sort(unique(region))
    k=length(uniregion)
    res1=list()
    res2=data.frame(region=uniregion,x=NA,y=NA)
    res2$region=as.character(res2$region)
    for (i in 1:k){
        ins=censordat[censordat$r %in% uniregion[i],]
        out=censordat[! censordat$r %in% uniregion[i],]
        res1[[i]]=unique(out[out$p %in% ins$p,1])
        res2[i,2:3]=centroid.polygon(dat[dat$r==uniregion[i],2:3])
    }
    names(res1)=uniregion
    return(list(nbr=res1,centroid=res2))
}

##' Produce a Dorling Cartogram.
##' 
##' @param name A vector of region names.
##' @param centroidx A vector of x-coordinates of the regions.
##' @param centroidy A vector of y-coordinates of the regions.
##' @param density A vector of the variable of interest. It will be used as the radii of the circles.
##' @param nbr A list of the neighbors of every region. Each element is a vector of all the neighbor names of a region. If nbr=NULL, then it is assumed that no region has any neighbors. If nbr is not NULL, then names should be given to all the elements of the list, for matching the neighbors with the host region name, otherwise the parameter "name" (a character vector) will be used as the element names of nbr. Besides, any values in nbr that are not in "name" will be removed. The length of nbr could be different from the length of "name", but any element in nbr whose name is not in "name" will be removed too.
##' @param tolerance Tolerant value for the sum of overlapped radii.
##' @param dist.ratio The threshold to determine whether an attract force is added. It is applied to the ratio of the distance between two centroids, and the sum of those two radii.
##' @param iteration The limit of the number of iterations. Default to be 9999.
##' @param animation Whether to show the movements of centroids.
##' @param sleep.time Only works when animation=TRUE.
##' @example inst/example.R
##' @export
##' 
dorling = function(name, centroidx, centroidy, density, nbr=NULL, tolerance=0.1, dist.ratio=2, iteration=9999, animation=TRUE, sleep.time=0.3, ...){
    n=length(name)
    stopifnot(n==length(centroidx), n==length(centroidy), n==length(density), is.numeric(iteration))
    
    # identify all the names
    name=as.character(name)
    if (is.null(names(nbr)) && sum(duplindex <- duplicated(name))) {
        name[duplindex]=paste(name[duplindex],name[duplindex],1:sum(duplindex),sep="_")
    }
    
    # clean "nbr"
    if (!is.null(nbr)) {        
        if (is.null(names(nbr))) {
            stopifnot(n==length(nbr))
            names(nbr)=name
        } else {
            nbr=nbr[names(nbr) %in% name]
        }
        if (any(!unlist(nbr) %in% name)) {
            for (i in 1:n){
                nbr[[i]]=nbr[[i]][nbr[[i]] %in% name]
            }
        }
    }

    # Set up the data
    dat=data.frame(name=name,x=centroidx,y=centroidy,density=density,stringsAsFactors=FALSE)
    rownames(dat)=dat$name
    
    # original distance
    origindist=as.matrix(dist(dat[,2:3]))
    
    # rescale the density (the radius)
    dat$density=dat$density/max(dat$density)*mean(origindist)/5
    
    # the closest distance for paired centroids
    circleDist=outer(dat$density,dat$density,"+")
    diag(circleDist)=0
    colnames(circleDist)=rownames(circleDist)=name
    
    # set up initial values
    # crtloc is the current centroid locations
    # frc is the force, including repel force and attract force
    crtloc=frc=dat[,2:3]
    crtDist=origindist
    s=0
    err=circleDist-crtDist
    
    while (sum(sapply(err,max,0))>tolerance) {
        s = s + 1
        if (!is.null(iteration) && s>iteration) {
            warning("Reach the largest iteration limit.")
            break
        }
        if (s%%10==0) cat("Iteration: ",s,"\n")
        if (animation) {
            plot(y~x,crtloc,type='p',col=2,pch=20,...)
            circle(crtloc$x,crtloc$y,dat$density)
            text(crtloc$x,crtloc$y,dat$name,cex=0.8)
            Sys.sleep(sleep.time)
        }
               
        frc$xforce=frc$yforce=frc$xattract=frc$yattract=frc$xrepel=frc$yrepel=0.00000
        
        # Calculate the repel force
        idx = circleDist > crtDist
        idx = idx & lower.tri(idx)
        err = circleDist-crtDist
        for (i in which(rowSums(idx)>0)){
            for (j in which(idx[i,1:(i-1)])){
                ratio=(circleDist[i,j]-crtDist[i,j])/2/crtDist[i,j]
                frc$xrepel[i]=frc$xrepel[i]+ratio*(crtloc$x[i]-crtloc$x[j])
                frc$xrepel[j]=frc$xrepel[j]+ratio*(crtloc$x[j]-crtloc$x[i])
                frc$yrepel[i]=frc$yrepel[i]+ratio*(crtloc$y[i]-crtloc$y[j])
                frc$yrepel[j]=frc$yrepel[j]+ratio*(crtloc$y[j]-crtloc$y[i])
            }
        }
        
        # Calculate the attract force
        for (i in 1:length(nbr)){
            for (j in 1:length(nbr[[i]])){
                crtstate=names(nbr)[i]
                crtnbr=which(rownames(crtDist)==nbr[[i]][j])
                distratio=crtDist[crtstate,crtnbr]/circleDist[crtstate,crtnbr]
                if (distratio > dist.ratio){
                    ratio=(crtDist[crtstate,crtnbr]-circleDist[crtstate,crtnbr])/(round(s/10)+8)/crtDist[crtstate,crtnbr]
                    frc$xattract[i]=frc$xattract[i]-ratio*(crtloc$x[i]-crtloc$x[crtnbr])
                    frc$xattract[crtnbr]=frc$xattract[crtnbr]-ratio*(crtloc$x[crtnbr]-crtloc$x[i])
                    frc$yattract[i]=frc$yattract[i]-ratio*(crtloc$y[i]-crtloc$y[crtnbr])
                    frc$yattract[crtnbr]=frc$yattract[crtnbr]-ratio*(crtloc$y[crtnbr]-crtloc$y[i])
                }
            }
        }
        
        # Find the final force
        frc$xforce=frc$xrepel+frc$xattract
        frc$yforce=frc$yrepel+frc$yattract
        
        # Reduce the force if it changes the relative direction of the neighbors
        closest=data.frame(cbind(rownames(crtDist),rownames(crtDist)[nnbr(crtDist,k=1)]))
        closest$xdist=apply(closest,1,function(xv){abs(crtloc[xv[1],1]-crtloc[xv[2],1])})
        closest$ydist=apply(closest,1,function(xv){abs(crtloc[xv[1],2]-crtloc[xv[2],2])})
        closest$xforce=abs(frc$xforce)
        closest$yforce=abs(frc$yforce)
        closest$xratio=closest$xdist/closest$xforce
        closest$yratio=closest$ydist/closest$yforce
        closest$ratio=pmin(closest$xratio,closest$yratio,na.rm=TRUE)
        closest$ratio[closest$ratio>1]=1
        frc$xforce=frc$xforce*closest$ratio
        frc$yforce=frc$yforce*closest$ratio
        
        crtloc=crtloc+frc[,8:7]
        crtDist=as.matrix(dist(crtloc))
    }
    
    plot(y~x,crtloc,type='p',col=2,pch=20,...)
    circle(crtloc$x,crtloc$y,dat$density)
    text(crtloc$x,crtloc$y,dat$name,cex=0.8)
}
